"use client";
import {useEffect,useRef,useState} from "react";
import {DerivWS} from "../lib/deriv";

type Tab="Dashboard"|"Bot Builder"|"Chart";
type Mode="Demo"|"Real";
type Account={account_id:string;account_type?:string;balance?:number;currency?:string};
type Market={symbol:string;name:string};
type Block={id:string;title:string;group:string;x:number;y:number};
const tabs:Tab[]=["Dashboard","Bot Builder","Chart"];
const fallback:Market[]=["10","25","50","75","100"].map(x=>({symbol:`R_${x}`,name:`Volatility ${x} Index`})).concat(["10","25","50","75","100"].map(x=>({symbol:`1HZ${x}V`,name:`Volatility ${x} (1s) Index`})));
const palette=["Trade parameters","Purchase conditions","Sell conditions","Restart trading conditions","If / Do","Comparison","Number","Arithmetic","Text","Set variable","Get variable","Time / Date","Contract information"];
const initial:Block[]=[{id:"trade",title:"1. Trade parameters",group:"Trading",x:35,y:35},{id:"purchase",title:"2. Purchase conditions",group:"Trading",x:35,y:390},{id:"sell",title:"3. Sell conditions",group:"Trading",x:510,y:35},{id:"restart",title:"4. Restart trading conditions",group:"Trading",x:510,y:245}];
const money=(v:number|null|undefined,c="USD")=>typeof v==="number"?`${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${c}`:`0.00 ${c}`;
function Logo(){return <div className="fxLogo">Deriv<span>FX</span></div>}
function AIcon({mode}:{mode:Mode}){return mode==="Real"?<span className="roundFlag">🇺🇸</span>:<span className="roundCoin">Ð</span>}
function Svg({type}:{type:string}){if(type==="home")return <svg viewBox="0 0 24 24"><path d="m3 11 9-8 9 8v9h-6v-6H9v6H3z"/></svg>;if(type==="blocks")return <svg viewBox="0 0 24 24"><path d="M4 4h7v5h2V4h7v7h-5v2h5v7h-7v-5h-2v5H4v-7h5v-2H4z"/></svg>;return <svg viewBox="0 0 24 24"><path d="M3 20V4m0 16h18M6 16l4-5 4 3 6-8"/></svg>}
export default function DerivFX(){
 const[loading,setLoading]=useState(true),[auth,setAuth]=useState(false),[tab,setTab]=useState<Tab>("Dashboard"),[mode,setMode]=useState<Mode>("Demo"),[accounts,setAccounts]=useState<Account[]>([]),[balance,setBalance]=useState<number|null>(null),[currency,setCurrency]=useState("USD"),[accountOpen,setAccountOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[running,setRunning]=useState(false),[symbol,setSymbol]=useState("R_50"),[markets,setMarkets]=useState<Market[]>(fallback),[price,setPrice]=useState<number|null>(null),[history,setHistory]=useState<number[]>([]),[blocks,setBlocks]=useState<Block[]>(initial),[toolbox,setToolbox]=useState(false),[transactions,setTransactions]=useState(false),[stake,setStake]=useState(1),[duration,setDuration]=useState(1),[contract,setContract]=useState("CALL");
 const accountWs=useRef<DerivWS|null>(null),marketWs=useRef<WebSocket|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),workspace=useRef<HTMLDivElement|null>(null),drag=useRef<{id:string;dx:number;dy:number}|null>(null);
 const login=()=>{setBusy(true);location.href="/api/auth/login"};const signup=()=>{setBusy(true);location.href="/api/auth/login?mode=signup"};
 const load=async()=>{const r=await fetch("/api/deriv/accounts",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j?.error||"Unable to load accounts");const a=(j.data||j.accounts||[]) as Account[];setAccounts(a);return a};
 const connect=async(m:Mode,list?:Account[])=>{try{accountWs.current?.close();const a=list||await load();const wanted=a.find(x=>String(x.account_type||"").toLowerCase()===m.toLowerCase());if(!wanted?.account_id)throw new Error(`No ${m.toLowerCase()} account available`);const r=await fetch("/api/deriv/otp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId:wanted.account_id}),cache:"no-store"}),j=await r.json();if(!r.ok||!j.data?.url)throw new Error(j?.errors?.[0]?.message||"Unable to connect account");const w=new DerivWS();accountWs.current=w;await w.connect(j.data.url);setMode(m);setCurrency(wanted.currency||"USD");setBalance(typeof wanted.balance==="number"?wanted.balance:null);w.balance(x=>{const b=Number((x as {balance?:{balance?:number}}).balance?.balance);if(Number.isFinite(b))setBalance(b)});return true}catch(e){setNotice(e instanceof Error?e.message:"Unable to connect");return false}};
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/auth/session",{cache:"no-store"}),j=await r.json();setAuth(!!j.authenticated);if(j.authenticated){const a=await load();await connect(a.some(x=>String(x.account_type||"").toLowerCase()==="real")?"Real":"Demo",a)}}catch(e){console.error(e)}finally{setLoading(false)}})();return()=>{accountWs.current?.close();marketWs.current?.close();if(timer.current)clearInterval(timer.current)}},[]);
 useEffect(()=>{const w=new WebSocket("wss://api.derivws.com/trading/v1/options/ws/public");marketWs.current=w;w.onopen=()=>w.send(JSON.stringify({active_symbols:"brief",req_id:1}));w.onmessage=e=>{try{const m=JSON.parse(e.data) as {msg_type?:string;active_symbols?:Array<Record<string,string>>;history?:{prices?:unknown[]};tick?:{quote?:number}};if(m.msg_type==="active_symbols"){const a=(m.active_symbols||[]).map(x=>({symbol:x.underlying_symbol||x.symbol,name:x.underlying_symbol_name||x.display_name||x.symbol})).filter(x=>/volatility/i.test(x.name)||/^R_\d+$/.test(x.symbol)||/^1HZ\d+V$/.test(x.symbol));if(a.length)setMarkets(a.filter((x,i,z)=>z.findIndex(y=>y.symbol===x.symbol)===i))}if(m.msg_type==="history"){const p=(m.history?.prices||[]).map(Number).filter(Number.isFinite);setHistory(p.slice(-160));if(p.length)setPrice(p[p.length-1])}if(m.msg_type==="tick"&&typeof m.tick?.quote==="number"){setPrice(m.tick.quote);setHistory(p=>[...p.slice(-159),m.tick!.quote as number])}}catch{}};return()=>w.close()},[]);
 useEffect(()=>{const w=marketWs.current;if(!w||w.readyState!==WebSocket.OPEN)return;w.send(JSON.stringify({ticks_history:symbol,count:160,end:"latest",style:"ticks",req_id:2}));w.send(JSON.stringify({ticks:symbol,subscribe:1,req_id:3}))},[symbol,markets]);
 useEffect(()=>{const move=(e:PointerEvent)=>{const d=drag.current,r=workspace.current;if(!d||!r)return;const b=r.getBoundingClientRect();setBlocks(x=>x.map(q=>q.id===d.id?{...q,x:Math.max(5,e.clientX-b.left-d.dx),y:Math.max(5,e.clientY-b.top-d.dy)}:q))};const up=()=>drag.current=null;addEventListener("pointermove",move);addEventListener("pointerup",up);return()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up)}},[]);
 const startDrag=(e:React.PointerEvent,id:string)=>{const b=blocks.find(x=>x.id===id),r=workspace.current;if(!b||!r)return;const q=r.getBoundingClientRect();drag.current={id,dx:e.clientX-q.left-b.x,dy:e.clientY-q.top-b.y}};
 const addBlock=(title:string)=>{setBlocks(x=>[...x,{id:`${Date.now()}${x.length}`,title,group:"Logic",x:100+(x.length%3)*330,y:80+Math.floor(x.length/3)*180}]);setToolbox(false)};
 const logout=async()=>{setBusy(true);accountWs.current?.close();if(timer.current)clearInterval(timer.current);await fetch("/api/auth/logout",{method:"POST"});location.href="/"};
 const choose=async(m:Mode)=>{if(auth&&m!==mode)await connect(m);else if(!auth)login();setAccountOpen(false)};
 const execute=()=>{if(!auth)return login();if(!accountWs.current)return setNotice("Deriv account is not connected.");if(running){if(timer.current)clearInterval(timer.current);timer.current=null;setRunning(false);setNotice("Bot stopped");return}const once=()=>accountWs.current?.proposal({amount:stake,basis:"stake",contract_type:contract,currency,duration,duration_unit:"t",underlying_symbol:symbol},p=>{const q=p as {error?:{message?:string};proposal?:{id?:string;ask_price?:number|string}};if(q.error)return setNotice(q.error.message||"Proposal failed");const id=q.proposal?.id,price=Number(q.proposal?.ask_price);if(!id||!Number.isFinite(price))return setNotice("No valid proposal");accountWs.current?.buy(id,price,b=>{const z=b as {error?:{message?:string};buy?:{contract_id?:number}};setNotice(z.error?.message||(z.buy?.contract_id?`Contract ${z.buy.contract_id} purchased`:"Contract purchased"))})});setRunning(true);setNotice("Bot is running");once();timer.current=setInterval(once,Math.max(3000,duration*2000))};
 if(loading)return <div className="loaderScreen"><Logo/><div className="loaderSpinner"/><p>Loading DerivFX…</p></div>;
 return <main className="dbotApp">
  <header className="dbotTopbar"><Logo/><div className="accountArea">{auth?<button className="accountSummary" onClick={()=>setAccountOpen(x=>!x)}><AIcon mode={mode}/><span><em>{mode} account</em><strong>{money(balance,currency)}</strong></span><b>{accountOpen?"⌃":"⌄"}</b></button>:<div className="authButtons"><button onClick={login}>Log in</button><button onClick={signup}>Sign up</button></div>}
   {accountOpen&&auth&&<div className="accountMenu"><div className="accountTabs"><button className={mode==="Real"?"selected":""} onClick={()=>choose("Real")}>Real</button><button className={mode==="Demo"?"selected":""} onClick={()=>choose("Demo")}>Demo</button></div><h3>Deriv accounts <span>⌃</span></h3>{(["Real","Demo"] as Mode[]).map(m=>{const a=accounts.find(x=>String(x.account_type||"").toLowerCase()===m.toLowerCase());return <button className={`accountRow ${m===mode?"selected":""}`} key={m} onClick={()=>choose(m)}><AIcon mode={m}/><span><b>{m==="Real"?(a?.currency||"USD"):"Demo"}</b><small>{a?.account_id||"Connect account"}</small></span><strong>{money(a?.balance??(m===mode?balance:0),a?.currency||currency)}</strong></button>})}<button className="traderHub">Looking for CFD accounts? Go to Trader's Hub</button><div className="logoutRow"><button onClick={logout}>Logout&nbsp; →</button></div></div>}
  </div></header>
  <nav className="dbotTabs">{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}><Svg type={t==="Dashboard"?"home":t==="Bot Builder"?"blocks":"chart"}/><span>{t}</span></button>)}</nav>
  {tab==="Dashboard"&&<section className="dashboardPage"><div className="dashboardIntro"><h1>Load or build your bot</h1><p>Import a bot from your computer or Google Drive, build it from scratch, or start with a quick strategy.</p></div><div className="dashboardChoices"><button><i>▯</i><b>Local</b></button><button><i>◆</i><b>Google Drive</b></button><button onClick={()=>setTab("Bot Builder")}><i>✣</i><b>Bot Builder</b></button><button onClick={()=>setTab("Bot Builder")}><i>◈</i><b>Quick strategy</b></button></div>{!auth&&<div className="loginPrompt"><h2>Connect your Deriv account</h2><p>Log in or sign up to connect a Demo or Real account.</p><button onClick={login}>Log in</button><button onClick={signup}>Sign up</button></div>}</section>}
  {tab==="Bot Builder"&&<section className="builderPage"><div className="builderToolbar"><button className="blocksButton" onClick={()=>setToolbox(x=>!x)}>☷ Blocks Menu　⌄</button><button className="quickButton">Quick strategy</button>{toolbox&&<aside className="toolbox">{palette.map(p=><button key={p} onClick={()=>addBlock(p)}>{p}<b>+</b></button>)}</aside>}</div><div className="workspaceShell"><aside className="workspaceRail"><button>↻</button><button>▱</button><button>▣</button><button>↶</button><button>↷</button><button>＋</button><button>－</button></aside><div className="workspace" ref={workspace}>{blocks.map(b=><article key={b.id} className="block" style={{left:b.x,top:b.y}} onPointerDown={e=>startDrag(e,b.id)}><header>⠿　{b.title}</header><div className="blockBody">{b.id==="trade"?<><label>Market <select defaultValue="Derived"><option>Derived</option></select></label><label>Contract <select value={contract} onChange={e=>setContract(e.target.value)}><option value="CALL">Rise / Call</option><option value="PUT">Fall / Put</option></select></label><label>Stake <input type="number" value={stake} min="0.35" step="0.01" onChange={e=>setStake(Number(e.target.value))}/></label><label>Duration <input type="number" value={duration} min="1" onChange={e=>setDuration(Number(e.target.value))}/> ticks</label><div className="socket">Run once at start:</div></>:b.id==="purchase"?<><label>Purchase <select defaultValue="Rise"><option>Rise</option><option>Fall</option></select></label><div className="socket">●</div></>:b.id==="sell"?<><span>if</span><div className="slot">Sell is available</div><span>then</span></>:b.id==="restart"?<div className="slot">Trade again</div>:<><b>{b.title}</b><div className="slot">Drop block here</div></>}</div></article>)}<span className="workspaceHint">Drag blocks to build your bot</span></div></div></section>}
  {tab==="Chart"&&<section className="chartPage"><div className="chartTop"><div><small>Live market</small><h2>{markets.find(x=>x.symbol===symbol)?.name||symbol}</h2></div><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{markets.map(x=><option key={x.symbol} value={x.symbol}>{x.name}</option>)}</select><b className="live">● LIVE</b></div><div className="chartPrice">{price==null?"—":price.toFixed(4)} <small>real-time ticks</small></div><div className="chartCanvas">{history.length>1&&<svg viewBox="0 0 1000 420" preserveAspectRatio="none"><path d={history.map((v,i)=>{const min=Math.min(...history),max=Math.max(...history),x=15+i/(history.length-1)*970,y=395-(v-min)/(max-min||1)*370;return `${i?"L":"M"}${x},${y}`}).join(" ")} fill="none" stroke="#ff4050" strokeWidth="3"/></svg>}</div><div className="chartFooter"><span>{markets.length} volatility indices available</span><span>{symbol}</span></div></section>}
  <section className={`executionBar ${transactions?"expanded":""}`}>{transactions&&<div className="transactionsPanel"><div className="transactionTabs"><button className="active">Summary</button><button>Transactions</button><button>Journal</button></div><div className="transactionSummary"><b>{running?"Bot is running":"Bot is not running"}</b><span>Account: {mode}</span><span>Balance: {money(balance,currency)}</span></div></div>}<button className={`runButton ${running?"stop":""}`} onClick={execute}>{running?"■ Stop":"▶ Run"}</button><div className="runStatus"><small>Execution</small><b>{running?"Bot is running":"Bot is not running"}</b></div><button className="transactionsButton" onClick={()=>setTransactions(x=>!x)}>Open transactions　⌃</button></section>
  {notice&&<button className="notice" onClick={()=>setNotice("")}>{notice}　×</button>}{busy&&<div className="busyOverlay"><div className="loaderSpinner"/><span>Connecting…</span></div>}
 </main>;
}
