"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {DerivWS} from "../lib/deriv";

type AccountMode="Demo"|"Real";
type DerivAccount={account_id:string;account_type?:string;balance?:number;currency?:string;status?:string;group?:string};
type MarketSymbol={symbol:string;name:string;market?:string;submarket?:string;pip?:number};

const tabs=["Dashboard","Bot Builder","AI Bots","Quick Bot","Free Bots","Signals","Analysis","Auto Trader","Deriv Course"];
const VOLATILITY_FALLBACK:MarketSymbol[]=[
 {symbol:"R_10",name:"Volatility 10 Index"},{symbol:"R_25",name:"Volatility 25 Index"},{symbol:"R_50",name:"Volatility 50 Index"},{symbol:"R_75",name:"Volatility 75 Index"},{symbol:"R_100",name:"Volatility 100 Index"},
 {symbol:"1HZ10V",name:"Volatility 10 (1s) Index"},{symbol:"1HZ25V",name:"Volatility 25 (1s) Index"},{symbol:"1HZ50V",name:"Volatility 50 (1s) Index"},{symbol:"1HZ75V",name:"Volatility 75 (1s) Index"},{symbol:"1HZ100V",name:"Volatility 100 (1s) Index"}
];

function AccountIcon({mode}:{mode:AccountMode}){return mode==="Real"?<span className="accountFlag" aria-label="US dollar account">🇺🇸</span>:<span className="accountCoin" aria-label="Demo account">Ð</span>}
function DbBadge(){return <span className="dbBadge">DB</span>}

function LiveChart({symbol,price,prices,onSelect,symbols}:{symbol:string;price:number|null;prices:number[];onSelect:(s:string)=>void;symbols:MarketSymbol[]}){
 const width=900,height=300,pad=24;
 const min=Math.min(...prices),max=Math.max(...prices),range=max-min||1;
 const points=prices.map((v,i)=>{const x=pad+(i/Math.max(1,prices.length-1))*(width-pad*2);const y=height-pad-((v-min)/range)*(height-pad*2);return `${x},${y}`}).join(" ");
 const name=symbols.find(s=>s.symbol===symbol)?.name||symbol;
 return <section className="chartCard">
   <div className="chartHeader"><div><small>Live chart</small><h3>{name}</h3></div><div className="chartControls"><select value={symbol} onChange={e=>onSelect(e.target.value)}>{symbols.map(s=><option key={s.symbol} value={s.symbol}>{s.name}</option>)}</select><span className="liveDot">● LIVE</span></div></div>
   <div className="chartMeta"><b>{price==null?"—":price.toFixed(4)}</b><span>Real-time tick stream</span></div>
   <div className="chartCanvas"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" role="img" aria-label={`${name} live chart`}><defs><linearGradient id="dbChartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#ff4b55" stopOpacity=".22"/><stop offset="1" stopColor="#ff4b55" stopOpacity="0"/></linearGradient></defs><line x1="24" x2="876" y1="150" y2="150" stroke="#e8ecef"/><line x1="24" x2="876" y1="75" y2="75" stroke="#f0f2f4"/><line x1="24" x2="876" y1="225" y2="225" stroke="#f0f2f4"/><polyline points={`${pad},${height-pad} ${points} ${width-pad},${height-pad}`} fill="url(#dbChartFill)" stroke="none"/><polyline points={points} fill="none" stroke="#ff4b55" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/></svg></div>
   <div className="chartFooter"><span>{symbols.length} volatility indices available</span><span>Updates automatically</span></div>
 </section>
}

export default function DerivFX(){
 const [loading,setLoading]=useState(true),[authLoading,setAuthLoading]=useState(false),[tab,setTab]=useState("Dashboard"),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[speed,setSpeed]=useState<"FAST"|"SLOW">("FAST"),[open,setOpen]=useState(false),[menu,setMenu]=useState(false),[accountMenu,setAccountMenu]=useState(false);
 const [balance,setBalance]=useState<number|null>(null),[account,setAccount]=useState<AccountMode>("Demo"),[connected,setConnected]=useState(false),[authenticated,setAuthenticated]=useState(false),[accounts,setAccounts]=useState<DerivAccount[]>([]),[pos,setPos]=useState<any[]>([]);
 const [symbols,setSymbols]=useState<MarketSymbol[]>(VOLATILITY_FALLBACK),[selectedSymbol,setSelectedSymbol]=useState("R_50"),[price,setPrice]=useState<number|null>(null),[prices,setPrices]=useState<number[]>([]),[builderSaved,setBuilderSaved]=useState(false),[selectedBlock,setSelectedBlock]=useState("Trade parameters");
 const ws=useRef<DerivWS|null>(null),marketWs=useRef<WebSocket|null>(null),accountWrapRef=useRef<HTMLDivElement|null>(null);
 const login=(mode:"login"|"signup"="login")=>{setAuthLoading(true);location.href=mode==="signup"?"/api/auth/login?mode=signup":"/api/auth/login"};
 const loadAccounts=async()=>{const r=await fetch("/api/deriv/accounts",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error||j?.errors?.[0]?.message||"Unable to load Deriv accounts");const list=(j.data||j.accounts||[]) as DerivAccount[];setAccounts(list);return list};
 const connectAccount=async(mode:AccountMode,knownAccounts?:DerivAccount[])=>{try{setConnected(false);setBalance(null);ws.current?.close();const list=knownAccounts||await loadAccounts();const wanted=list.find(a=>String(a.account_type||"").toLowerCase()===(mode==="Demo"?"demo":"real"));if(!wanted?.account_id)throw new Error(`No ${mode.toLowerCase()} Deriv account is available`);const ar=await fetch("/api/deriv/otp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId:wanted.account_id}),cache:"no-store"});const oj=await ar.json(),wsUrl=oj.data?.url;if(!ar.ok||!wsUrl)throw new Error(oj.errors?.[0]?.message||"Unable to obtain authenticated WebSocket URL");setAccount(mode);setBalance(typeof wanted.balance==="number"?wanted.balance:null);const d=new DerivWS();ws.current=d;await d.connect(wsUrl);setConnected(true);d.balance(m=>{const b=(m as any).balance?.balance;if(typeof b==="number")setBalance(b)});d.portfolio(m=>setPos(((m as any).portfolio?.contracts)||[]));return true}catch(e){console.error(e);setConnected(false);return false}};
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/auth/session",{cache:"no-store"}),s=await r.json();setAuthenticated(!!s.authenticated);if(s.authenticated){const list=await loadAccounts();const preferred=list.find(a=>String(a.account_type||"").toLowerCase()==="real")?"Real":"Demo";await connectAccount(preferred as AccountMode,list)}}catch(e){console.error(e)}finally{setLoading(false)}})();return()=>ws.current?.close()},[]);
 useEffect(()=>{const socket=new WebSocket("wss://api.derivws.com/trading/v1/options/ws/public");marketWs.current=socket;socket.onopen=()=>socket.send(JSON.stringify({active_symbols:"brief",req_id:1}));socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.msg_type==="active_symbols"){const all=(m.active_symbols||[]).map((s:any)=>({symbol:s.underlying_symbol||s.symbol,name:s.underlying_symbol_name||s.display_name||s.symbol,market:s.market,submarket:s.submarket,pip:s.pip_size||s.pip})).filter((s:MarketSymbol)=>/volatility/i.test(s.name)||/^R_\d+$/.test(s.symbol)||/^1HZ\d+V$/.test(s.symbol));if(all.length){const unique=all.filter((s:MarketSymbol,i:number,a:MarketSymbol[])=>a.findIndex(x=>x.symbol===s.symbol)===i);setSymbols(unique);setSelectedSymbol(current=>unique.some(x=>x.symbol===current)?current:unique[0].symbol)}}}catch(err){console.error(err)}};socket.onerror=()=>{};return()=>{socket.close();marketWs.current=null}},[]);
 useEffect(()=>{const socket=marketWs.current;if(!socket||socket.readyState!==WebSocket.OPEN)return;socket.send(JSON.stringify({ticks_history:selectedSymbol,count:80,end:"latest",style:"ticks",req_id:20}));socket.send(JSON.stringify({ticks:selectedSymbol,subscribe:1,req_id:21}));const handler=(e:MessageEvent)=>{try{const m=JSON.parse(e.data);if(m.msg_type==="history"&&Array.isArray(m.history?.prices)){const next=m.history.prices.map(Number).filter(Number.isFinite);if(next.length){setPrices(next);setPrice(next[next.length-1])}}if(m.msg_type==="tick"&&m.tick?.quote!=null){const q=Number(m.tick.quote);setPrice(q);setPrices(prev=>[...prev.slice(-119),q])}}catch{}};socket.addEventListener("message",handler);return()=>socket.removeEventListener("message",handler)},[selectedSymbol,symbols]);
 useEffect(()=>{const onPointerDown=(e:PointerEvent)=>{if(accountMenu&&accountWrapRef.current&&!accountWrapRef.current.contains(e.target as Node))setAccountMenu(false)};document.addEventListener("pointerdown",onPointerDown);return()=>document.removeEventListener("pointerdown",onPointerDown)},[accountMenu]);
 const chooseAccount=async(mode:AccountMode)=>{if(!authenticated){setAccountMenu(false);login();return}if(mode===account){setAccountMenu(false);return}const ok=await connectAccount(mode);if(ok)setAccountMenu(false)};
 const logout=async()=>{try{setAuthLoading(true);ws.current?.close();await fetch("/api/auth/logout",{method:"POST"})}finally{setAuthenticated(false);setConnected(false);setBalance(null);setAccounts([]);setAccountMenu(false);setRunning(false);setPaused(false);setAuthLoading(false);location.href="/"}};
 const toggleRun=()=>{if(!authenticated){login();return}if(!running){setRunning(true);setPaused(false)}else setPaused(p=>!p)};
 const stop=()=>{setRunning(false);setPaused(false)};
 const money=(v:number|undefined|null)=>typeof v==="number"?v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):"0.00";
 const demoAccount=accounts.find(a=>String(a.account_type||"").toLowerCase()==="demo"),realAccount=accounts.find(a=>String(a.account_type||"").toLowerCase()==="real");
 if(loading)return <div className="loaderScreen"><DbBadge/><div className="loaderSpinner"/><p>Loading Deriv Bot workspace…</p><small>Connecting your Deriv account</small></div>;
 return <main className="app">
  <header className="dbTop">
   <button className="dbMenuButton" onClick={()=>setMenu(true)} aria-label="Open menu">☰</button><DbBadge/><div className="dbBrand"><b>DerivFX</b><small>Bot</small></div><div className="dbTopSpacer"/>
   <button className="currencyDb"><b>USD</b><span>⌄</span></button>
   <div className="accountWrap" ref={accountWrapRef}><button className="walletDb" onClick={()=>setAccountMenu(v=>!v)} aria-expanded={accountMenu}><AccountIcon mode={account}/><span>{authenticated?money(balance):"0.00"} USD</span><span className="walletArrowDb">{accountMenu?"⌃":"⌄"}</span></button>
    {accountMenu&&<div className="accountPanelDb"><div className="accountTabs"><button className={account==="Real"?"selected":""} onClick={()=>chooseAccount("Real")}>Real</button><button className={account==="Demo"?"selected":""} onClick={()=>chooseAccount("Demo")}>Demo</button></div><div className="accountHeading"><b>Deriv accounts</b><span>⌃</span></div>
      <button className={account==="Real"?"accountOption selected":"accountOption"} onClick={()=>chooseAccount("Real")}><AccountIcon mode="Real"/><span className="accountText"><b>USD</b><small>{realAccount?.account_id||"Real account"}</small></span><strong>{money(realAccount?.balance)} USD</strong></button>
      <button className={account==="Demo"?"accountOption selected":"accountOption"} onClick={()=>chooseAccount("Demo")}><AccountIcon mode="Demo"/><span className="accountText"><b>Demo</b><small>{demoAccount?.account_id||"Demo account"}</small></span><strong>{money(demoAccount?.balance)} USD</strong></button>
      <button className="traderHub" onClick={()=>{setAccountMenu(false);location.href="https://app.deriv.com/my"}}>Looking for CFD accounts? Go to Trader's Hub</button><div className="logoutRow"><button onClick={logout}>Logout <span>⇥</span></button></div>
    </div>}
   </div>
   {!authenticated&&<><button className="dbLogin" onClick={()=>login("login")}>Log in</button><button className="dbSignup" onClick={()=>login("signup")}>Sign up</button></>}
  </header>
  {menu&&<aside className="dbDrawer"><button className="drawerClose" onClick={()=>setMenu(false)}>×</button><h2>DerivFX Bot</h2>{!authenticated?<><button onClick={()=>login("login")}>Log in to Deriv</button><button onClick={()=>login("signup")}>Sign up</button></>:<button onClick={()=>{setMenu(false);setAccountMenu(true)}}>Switch account</button>}<p>Account: {authenticated?account:"Not connected"}</p><p>Trading History</p><p>Settings</p></aside>}
  <nav className="tabs">{tabs.map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {tab==="Dashboard"&&<section className="dbDashboard"><div className="loadHeader"><h1>Load or build your bot</h1><p>Import a bot from your device or Google Drive, build it from scratch, or start with a quick strategy.</p></div><div className="dbChoices"><button onClick={()=>{const input=document.createElement("input");input.type="file";input.accept=".xml,.json";input.onchange=()=>{};input.click()}}><span>▣</span><b>Local</b></button><button onClick={()=>alert("Google Drive import can be connected here when Drive access is enabled.")}><span>◆</span><b>Google Drive</b></button><button onClick={()=>setTab("Bot Builder")}><span>♣</span><b>Bot Builder</b></button><button onClick={()=>setTab("Quick Bot")}><span>◈</span><b>Quick strategy</b></button></div><LiveChart symbol={selectedSymbol} price={price} prices={prices.length?prices:[0,0]} onSelect={setSelectedSymbol} symbols={symbols}/></section>}
  {tab==="Bot Builder"&&<section className="botBuilder"><div className="builderToolbar"><button className="blocksMenu">Blocks Menu ⌄</button><button className="quickStrategy" onClick={()=>setTab("Quick Bot")}>Quick strategy</button><span className="builderHint">{builderSaved?"Bot saved locally":"Untitled Bot"}</span></div><div className="builderLayout"><aside className="builderRail"><button title="Refresh">↻</button><button title="Load">▱</button><button title="Save" onClick={()=>setBuilderSaved(true)}>▣</button><button title="Blocks">▤</button><button title="Undo">↶</button><button title="Redo">↷</button><button title="Zoom in">⊕</button><button title="Zoom out">⊖</button></aside><div className="workspace"><div className="block blockTrade" onClick={()=>setSelectedBlock("Trade parameters")}><div className="blockTitle">▣ 1. Trade parameters</div><div className="blockBody"><label>Market <select><option>Derived</option></select></label><label>Index <select value={selectedSymbol} onChange={e=>setSelectedSymbol(e.target.value)}>{symbols.map(s=><option key={s.symbol} value={s.symbol}>{s.name}</option>)}</select></label><label>Trade Type <select><option>Rise/Fall</option><option>Digits</option><option>Higher/Lower</option></select></label><label>Contract Type <select><option>Both</option><option>Call</option><option>Put</option></select></label><label>Default Candle Interval <select><option>1 minute</option><option>5 minutes</option><option>15 minutes</option></select></label><label className="check"><input type="checkbox"/> Restart buy/sell on error</label><label className="check"><input type="checkbox" defaultChecked/> Restart last trade on error</label><div className="socketRow">Run once at start:</div><div className="socketRow">Trade options:</div><label>Duration <select><option>Ticks</option><option>Seconds</option></select></label><label>Stake <input defaultValue="1"/></label></div></div>
   <div className="block blockPurchase" onClick={()=>setSelectedBlock("Purchase conditions")}><div className="blockTitle">▣ 2. Purchase conditions</div><div className="blockBody"><label>Purchase <select><option>Rise</option><option>Fall</option><option>Higher</option><option>Lower</option></select></label><label className="check"><input type="checkbox"/> Allow Bulk Purchase</label><label>No. of trades <input defaultValue="1"/></label></div></div>
   <div className="block blockSell" onClick={()=>setSelectedBlock("Sell conditions")}><div className="blockTitle">▣ 3. Sell conditions</div><div className="blockBody"><span>if</span><div className="condition">Sell is available → then</div></div></div>
   <div className="block blockRestart" onClick={()=>setSelectedBlock("Restart trading conditions")}><div className="blockTitle">▣ 4. Restart trading conditions</div><div className="blockBody"><div className="condition">Trade again</div></div></div>
   <div className="selectedBlockLabel">Selected: {selectedBlock}</div>
   </div><aside className="builderChart"><LiveChart symbol={selectedSymbol} price={price} prices={prices.length?prices:[0,0]} onSelect={setSelectedSymbol} symbols={symbols}/></aside></div></section>}
  {tab!=="Dashboard"&&tab!=="Bot Builder"&&<section className="tabEmpty"><h2>{tab}</h2><p>This DerivFX tab is ready for its connected tool. The DBot-style Dashboard and Bot Builder are live above.</p></section>}
  <section className="executionDb">{open&&<div className="transactionsDb"><div className="txHead"><b>Open Transactions ({pos.length})</b><button onClick={()=>setOpen(false)}>⌄</button></div>{pos.length?pos.map((p:any,i:number)=><div className="tx" key={i}><div><b>{p.underlying_symbol||p.symbol||"Volatility Index"}</b><small>{p.contract_type||"Contract"}</small></div><strong>{typeof p.profit==="number"?(p.profit>=0?"+":"")+p.profit.toFixed(2)+" USD":"Open"}</strong></div>):<div className="empty">No open transactions</div>}</div>}<div className="execRowDb"><button className="runDb" onClick={toggleRun}>{!running?"▶ Run":paused?"▶ Resume":"Ⅱ Pause"}</button><div className="statusDb"><small>Execution</small><b>{speed}</b></div>{running&&<button className="stopDb" onClick={stop}>■ Stop</button>}<button className="openBtnDb" onClick={()=>setOpen(!open)}>Open transaction {pos.length} {open?"⌃":"⌄"}</button></div></section>
  {authLoading&&<div className="authOverlay"><div className="loaderSpinner"/><b>Connecting to Deriv…</b></div>}
 </main>
}
